"""create py_word_pool table

Revision ID: 248a5d83389a
Revises: 263d6724c8c3
Create Date: 2020-07-05 03:55:09.165729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248a5d83389a'
down_revision = '263d6724c8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('py_word_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('py_word_pool')
    # ### end Alembic commands ###
