"""create py_keywords table

Revision ID: 263d6724c8c3
Revises: 
Create Date: 2020-07-05 03:46:32.154109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263d6724c8c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('py_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=60), nullable=False),
    sa.Column('response_cls', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('py_keywords')
    # ### end Alembic commands ###
