"""create_py_weather_location_map_table

Revision ID: 9df871e7081c
Revises: a14dde4984da
Create Date: 2020-07-15 00:57:50.724195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df871e7081c'
down_revision = 'a14dde4984da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('py_weather_location_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('weather_api_key', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location', 'weather_api_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('py_weather_location_map')
    # ### end Alembic commands ###
