"""create py_minion_image_pool table

Revision ID: a14dde4984da
Revises: 248a5d83389a
Create Date: 2020-07-05 03:56:14.774088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14dde4984da'
down_revision = '248a5d83389a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('py_minion_image_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('size', sa.String(length=30), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('py_minion_image_pool')
    # ### end Alembic commands ###
